//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_1933112.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appartment()
        {
            this.Buildings = new HashSet<Building>();
        }
    
        public int AppartmentID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> TenantID { get; set; }
        public Nullable<int> ManagerID { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual Tenant Tenant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Building> Buildings { get; set; }
    }
}
